---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'VPC: Legacy public and private subnets in four availability zones, a cloudonaut.io template'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'VPC Parameters'
      Parameters:
      - AZA
      - AZB
      - AZC
      - AZD
      - ClassB
      - VPC
      - SubnetAPublic
      - RouteTableAPublic
      - SubnetBPublic
      - RouteTableBPublic
      - SubnetCPublic
      - RouteTableCPublic
      - SubnetDPublic
      - RouteTableDPublic
      - SubnetAPrivate
      - RouteTableAPrivate
      - SubnetBPrivate
      - RouteTableBPrivate
      - SubnetCPrivate
      - RouteTableCPrivate
      - SubnetDPrivate
      - RouteTableDPrivate
Parameters:
  AZA:
    Description: 'AZ of A'
    Type: 'AWS::EC2::AvailabilityZone::Name'
  AZB:
    Description: 'AZ of B'
    Type: 'AWS::EC2::AvailabilityZone::Name'
  AZC:
    Description: 'AZ of C'
    Type: 'AWS::EC2::AvailabilityZone::Name'
  AZD:
    Description: 'AZ of D'
    Type: 'AWS::EC2::AvailabilityZone::Name'
  ClassB:
    Description: 'Class B of VPC (10.XXX.0.0/16)'
    Type: Number
    Default: 0
    ConstraintDescription: 'Must be in the range [0-255]'
    MinValue: 0
    MaxValue: 255
  VPC:
    Description: 'VPC'
    Type: 'AWS::EC2::VPC::Id'
  SubnetAPublic:
    Description: 'Subnet A public.'
    Type: 'AWS::EC2::Subnet::Id'
  RouteTableAPublic:
    Description: 'Route table A public.'
    Type: String
  SubnetBPublic:
    Description: 'Subnet B public.'
    Type: 'AWS::EC2::Subnet::Id'
  RouteTableBPublic:
    Description: 'Route table B public.'
    Type: String
  SubnetCPublic:
    Description: 'Subnet C public.'
    Type: 'AWS::EC2::Subnet::Id'
  RouteTableCPublic:
    Description: 'Route table C public.'
    Type: String
  SubnetDPublic:
    Description: 'Subnet D public.'
    Type: 'AWS::EC2::Subnet::Id'
  RouteTableDPublic:
    Description: 'Route table D public.'
    Type: String
  SubnetAPrivate:
    Description: 'Subnet A private.'
    Type: 'AWS::EC2::Subnet::Id'
  RouteTableAPrivate:
    Description: 'Route table A private.'
    Type: String
  SubnetBPrivate:
    Description: 'Subnet B private.'
    Type: 'AWS::EC2::Subnet::Id'
  RouteTableBPrivate:
    Description: 'Route table B private.'
    Type: String
  SubnetCPrivate:
    Description: 'Subnet C private.'
    Type: 'AWS::EC2::Subnet::Id'
  RouteTableCPrivate:
    Description: 'Route table C private.'
    Type: String
  SubnetDPrivate:
    Description: 'Subnet D private.'
    Type: 'AWS::EC2::Subnet::Id'
  RouteTableDPrivate:
    Description: 'Route table D private.'
    Type: String
Resources:
  Dummy:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref 'AWS::StackName'
Outputs:
  TemplateID:
    Description: 'cloudonaut.io template id'
    Value: 'vpc/vpc-4azs-legacy'
  StackName:
    Description: 'Stack name'
    Value: !Sub '${AWS::StackName}'
  AZs:
    Description: 'AZs'
    Value: 4
    Export:
      Name: !Sub '${AWS::StackName}-AZs'
  AZA:
    Description: 'AZ of A'
    Value: !Ref AZA
    Export:
      Name: !Sub '${AWS::StackName}-AZA'
  AZB:
    Description: 'AZ of B'
    Value: !Ref AZB
    Export:
      Name: !Sub '${AWS::StackName}-AZB'
  AZC:
    Description: 'AZ of C'
    Value: !Ref AZC
    Export:
      Name: !Sub '${AWS::StackName}-AZC'
  AZD:
    Description: 'AZ of D'
    Value: !Ref AZD
    Export:
      Name: !Sub '${AWS::StackName}-AZD'
  ClassB:
    Description: 'Class B.'
    Value: !Ref ClassB
    Export:
      Name: !Sub '${AWS::StackName}-ClassB'
  VPC:
    Description: 'VPC.'
    Value: !Ref VPC
    Export:
      Name: !Sub '${AWS::StackName}-VPC'
  SubnetsPublic:
    Description: 'Subnets public.'
    Value: !Join [',', [!Ref SubnetAPublic, !Ref SubnetBPublic, !Ref SubnetCPublic, !Ref SubnetDPublic]]
    Export:
      Name: !Sub '${AWS::StackName}-SubnetsPublic'
  SubnetsPrivate:
    Description: 'Subnets private.'
    Value: !Join [',', [!Ref SubnetAPrivate, !Ref SubnetBPrivate, !Ref SubnetCPrivate, !Ref SubnetDPrivate]]
    Export:
      Name: !Sub '${AWS::StackName}-SubnetsPrivate'
  RouteTablePrivate: # deprecated in v4, will be removed in v5
    Description: 'Route table private (deprecated in v4, will be removed in v5).'
    Value: !Ref RouteTableAPrivate
    Export:
      Name: !Sub '${AWS::StackName}-RouteTablePrivate'
  RouteTablePublic: # deprecated in v4, will be removed in v5
    Description: 'Route table public (deprecated in v4, will be removed in v5).'
    Value: !Ref RouteTableAPublic
    Export:
      Name: !Sub '${AWS::StackName}-RouteTablePublic'
  RouteTablesPrivate:
    Description: 'Route tables private.'
    Value: !Join [',', [!Ref RouteTableAPrivate, !Ref RouteTableBPrivate, !Ref RouteTableCPrivate, !Ref RouteTableDPrivate]]
    Export:
      Name: !Sub '${AWS::StackName}-RouteTablesPrivate'
  RouteTablesPublic:
    Description: 'Route tables public.'
    Value: !Join [',', [!Ref RouteTableAPublic, !Ref RouteTableBPublic, !Ref RouteTableCPublic, !Ref RouteTableDPublic]]
    Export:
      Name: !Sub '${AWS::StackName}-RouteTablesPublic'
  SubnetAPublic:
    Description: 'Subnet A public.'
    Value: !Ref SubnetAPublic
    Export:
      Name: !Sub '${AWS::StackName}-SubnetAPublic'
  RouteTableAPublic:
    Description: 'Route table A public.'
    Value: !Ref RouteTableAPublic
    Export:
      Name: !Sub '${AWS::StackName}-RouteTableAPublic'
  SubnetAPrivate:
    Description: 'Subnet A private.'
    Value: !Ref SubnetAPrivate
    Export:
      Name: !Sub '${AWS::StackName}-SubnetAPrivate'
  RouteTableAPrivate:
    Description: 'Route table A private.'
    Value: !Ref RouteTableAPrivate
    Export:
      Name: !Sub '${AWS::StackName}-RouteTableAPrivate'
  SubnetBPublic:
    Description: 'Subnet B public.'
    Value: !Ref SubnetBPublic
    Export:
      Name: !Sub '${AWS::StackName}-SubnetBPublic'
  RouteTableBPublic:
    Description: 'Route table B public.'
    Value: !Ref RouteTableBPublic
    Export:
      Name: !Sub '${AWS::StackName}-RouteTableBPublic'
  SubnetBPrivate:
    Description: 'Subnet B private.'
    Value: !Ref SubnetBPrivate
    Export:
      Name: !Sub '${AWS::StackName}-SubnetBPrivate'
  RouteTableBPrivate:
    Description: 'Route table B private.'
    Value: !Ref RouteTableBPrivate
    Export:
      Name: !Sub '${AWS::StackName}-RouteTableBPrivate'
  SubnetCPublic:
    Description: 'Subnet C public.'
    Value: !Ref SubnetCPublic
    Export:
      Name: !Sub '${AWS::StackName}-SubnetCPublic'
  RouteTableCPublic:
    Description: 'Route table C public.'
    Value: !Ref RouteTableCPublic
    Export:
      Name: !Sub '${AWS::StackName}-RouteTableCPublic'
  SubnetCPrivate:
    Description: 'Subnet C private.'
    Value: !Ref SubnetCPrivate
    Export:
      Name: !Sub '${AWS::StackName}-SubnetCPrivate'
  RouteTableCPrivate:
    Description: 'Route table C private.'
    Value: !Ref RouteTableCPrivate
    Export:
      Name: !Sub '${AWS::StackName}-RouteTableCPrivate'
  SubnetDPublic:
    Description: 'Subnet D public.'
    Value: !Ref SubnetDPublic
    Export:
      Name: !Sub '${AWS::StackName}-SubnetDPublic'
  RouteTableDPublic:
    Description: 'Route table D public.'
    Value: !Ref RouteTableDPublic
    Export:
      Name: !Sub '${AWS::StackName}-RouteTableDPublic'
  SubnetDPrivate:
    Description: 'Subnet D private.'
    Value: !Ref SubnetDPrivate
    Export:
      Name: !Sub '${AWS::StackName}-SubnetDPrivate'
  RouteTableDPrivate:
    Description: 'Route table D private.'
    Value: !Ref RouteTableDPrivate
    Export:
      Name: !Sub '${AWS::StackName}-RouteTableDPrivate'
